version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      all-dependencies:
        patterns:
          - "*"
        applies-to: version-updates
      dev-security-updates:
        patterns:
          - "*"
        applies-to: security-updates
        dependency-type: development

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      all-github-actions:
        patterns:
          - "*"
