// ──────────────────────────────────────────────────────────────
// AUTO-GENERATED by @cerios/salesforce-sobjectly (`sobjectly generate`).
// Do not edit manually; re-run the generator instead.
// ──────────────────────────────────────────────────────────────
// sobjectly-content-hash: sha256:9038e82fac6943728bf2730c068a27660f1a8a17be9ccc2fdacec158dd8892d7
// sobjectly-sobjects: Opportunity:fdb37f11d818,OpportunityStageName:50fa3319032b
/* eslint-disable */

/** Active values of Opportunity.Odd__c (picklist). */
export const OpportunityOddCustom = {
	"1": "1",
	_1: "_1",
	"-1": "-1",
	NaN: "NaN",
	new: "new",
	class: "class",
	constructor: "constructor",
	proto: "__proto__",
	a_b_c: "a\"b'c",
	"*/": "*/",
} as const;
export type OpportunityOddCustom = (typeof OpportunityOddCustom)[keyof typeof OpportunityOddCustom];

/** Active values of Opportunity.StageName (picklist). */
export const OpportunityStageNamePicklist = {
	Prospecting: "Prospecting",
	Closed_Won: "Closed Won",
	"Closed-Won": "Closed-Won",
	Proposal_Price_Quote: "Proposal/Price Quote",
	_3rd_Party: "3rd Party",
	"日本": "日本",
} as const;
export type OpportunityStageNamePicklist = (typeof OpportunityStageNamePicklist)[keyof typeof OpportunityStageNamePicklist];

export interface Opportunity {
	/** Odd__c (picklist) */
	Odd__c: OpportunityOddCustom | null;
	/** StageName (picklist) */
	StageName: OpportunityStageNamePicklist | null;
}

export type OpportunityCreateInput = Partial<Pick<Opportunity, "Odd__c" | "StageName">>;

export type OpportunityUpdateInput = Partial<Pick<Opportunity, "Odd__c" | "StageName">>;

export interface OpportunityStageName {

}

export type OpportunityStageNameCreateInput = Record<string, never>;

export type OpportunityStageNameUpdateInput = Record<string, never>;

/**
 * Maps every generated sObject to its read, create and update types and its relationships.
 * Pass it to the client: `new SalesforceClient<SObjectRegistry>({ ... })`.
 */
export interface SObjectRegistry {
	Opportunity: {
		read: Opportunity;
		create: OpportunityCreateInput;
		update: OpportunityUpdateInput;
		parents: Record<never, never>;
		children: Record<never, never>;
		externalIds: never;
		fieldKinds: Record<never, never>;
		recordTypes: never;
		polymorphicParents: Record<never, never>;
	};
	OpportunityStageName: {
		read: OpportunityStageName;
		create: OpportunityStageNameCreateInput;
		update: OpportunityStageNameUpdateInput;
		parents: Record<never, never>;
		children: Record<never, never>;
		externalIds: never;
		fieldKinds: Record<never, never>;
		recordTypes: never;
		polymorphicParents: Record<never, never>;
	};
}
