// ──────────────────────────────────────────────────────────────
// AUTO-GENERATED by @cerios/salesforce-sobjectly (`sobjectly generate`).
// Do not edit manually; re-run the generator instead.
// ──────────────────────────────────────────────────────────────
// sobjectly-content-hash: sha256:95416a3c5335b5c40c4f98bc6f68f1e9bbfde2ba1a503b64efffe9a0fdde0faf
// sobjectly-sobjects: Opportunity:3588274bf77d,OpportunityStageName:50fa3319032b
/* eslint-disable */

/** Active values of Opportunity.Odd__c (picklist). */
export enum OpportunityOddCustom {
	_1_2 = "1",
	_1 = "_1",
	_1_3 = "-1",
	NaN = "NaN",
	new = "new",
	class = "class",
	constructor = "constructor",
	proto = "__proto__",
	a_b_c = "a\"b'c",
	"*/" = "*/",
}

/** Active values of Opportunity.StageName (picklist). */
export enum OpportunityStageNamePicklist {
	Prospecting = "Prospecting",
	Closed_Won = "Closed Won",
	"Closed-Won" = "Closed-Won",
	Proposal_Price_Quote = "Proposal/Price Quote",
	_3rd_Party = "3rd Party",
	"日本" = "日本",
}

export interface Opportunity {
	/** Odd__c (picklist) */
	Odd__c: OpportunityOddCustom | null;
	/** StageName (picklist) */
	StageName: OpportunityStageNamePicklist | null;
}

export type OpportunityCreateInput = Partial<Pick<Opportunity, "Odd__c" | "StageName">>;

export type OpportunityUpdateInput = Partial<Pick<Opportunity, "Odd__c" | "StageName">>;

export interface OpportunityStageName {

}

export type OpportunityStageNameCreateInput = Record<string, never>;

export type OpportunityStageNameUpdateInput = Record<string, never>;

/**
 * Maps every generated sObject to its read, create and update types and its relationships.
 * Pass it to the client: `new SalesforceClient<SObjectRegistry>({ ... })`.
 */
export interface SObjectRegistry {
	Opportunity: {
		read: Opportunity;
		create: OpportunityCreateInput;
		update: OpportunityUpdateInput;
		parents: Record<never, never>;
		children: Record<never, never>;
		externalIds: never;
		fieldKinds: Record<never, never>;
		recordTypes: never;
		polymorphicParents: Record<never, never>;
	};
	OpportunityStageName: {
		read: OpportunityStageName;
		create: OpportunityStageNameCreateInput;
		update: OpportunityStageNameUpdateInput;
		parents: Record<never, never>;
		children: Record<never, never>;
		externalIds: never;
		fieldKinds: Record<never, never>;
		recordTypes: never;
		polymorphicParents: Record<never, never>;
	};
}
