// ──────────────────────────────────────────────────────────────
// AUTO-GENERATED by @cerios/salesforce-sobjectly (`sobjectly generate`).
// Do not edit manually; re-run the generator instead.
// ──────────────────────────────────────────────────────────────
// sobjectly-content-hash: sha256:e35ebd5cd0a60a6394d10ee51d38a581efe6ae0219408007ecbd003a032a02d9
// sobjectly-sobjects: Account:09bc6a76bda9,Case:85a3d855e653,Contact:76d28a660f17,Order_Shipped__e:8f1e103f20d9,Task:275ff5b41f4b,User:61bd56fbb4a9
/* eslint-disable */

import type { SalesforceAddress, SalesforceGeolocation } from "../../src/index";

/** Active values of Account.Industry (picklist). */
export const AccountIndustry = {
	Banking: "Banking",
	Energy: "Energy",
} as const;
export type AccountIndustry = (typeof AccountIndustry)[keyof typeof AccountIndustry];

/** Active values of Account.Type (picklist). */
export const AccountType = {
	Customer: "Customer",
	Partner: "Partner",
} as const;
export type AccountType = (typeof AccountType)[keyof typeof AccountType];

/** Account */
export interface Account {
	/** Id (id) */
	Id: string;
	/** AnnualRevenue (currency) */
	AnnualRevenue: number | null;
	/** BillingAddress (address) */
	BillingAddress: SalesforceAddress | null;
	/** CreatedDate (datetime) */
	CreatedDate: string;
	/** Description (textarea) */
	Description: string | null;
	/** External Id (string) */
	External_Id__c: string | null;
	/** Industry (picklist) */
	Industry: AccountIndustry | null;
	/** IsDeleted (boolean) */
	IsDeleted: boolean;
	/** Location (location) */
	Location__c: SalesforceGeolocation | null;
	/** Name (string) */
	Name: string;
	/** NumberOfEmployees (int) */
	NumberOfEmployees: number | null;
	/** OwnerId (reference) */
	OwnerId: string;
	/** ParentId (reference) */
	ParentId: string | null;
	/** Phone (phone) */
	Phone: string | null;
	/** Type (picklist) */
	Type: AccountType | (string & {}) | null;
	/** Website (url) */
	Website: string | null;
}

export type AccountCreateInput = Pick<Account, "Name"> & Partial<Pick<Account, "AnnualRevenue" | "Description" | "External_Id__c" | "Industry" | "Location__c" | "NumberOfEmployees" | "OwnerId" | "ParentId" | "Phone" | "Type" | "Website">>;

export type AccountUpdateInput = Partial<Pick<Account, "AnnualRevenue" | "Description" | "External_Id__c" | "Industry" | "Location__c" | "Name" | "NumberOfEmployees" | "OwnerId" | "ParentId" | "Phone" | "Type" | "Website">>;

/** Active values of Case.Channel__c (combobox). */
export const CaseChannelCustom = {
	Web: "Web",
	Phone: "Phone",
} as const;
export type CaseChannelCustom = (typeof CaseChannelCustom)[keyof typeof CaseChannelCustom];

/** Active values of Case.Priority (picklist). */
export const CasePriority = {
	High: "High",
	Low: "Low",
} as const;
export type CasePriority = (typeof CasePriority)[keyof typeof CasePriority];

/** Active values of Case.Status (picklist). */
export const CaseStatus = {
	New: "New",
	Working: "Working",
	Closed: "Closed",
} as const;
export type CaseStatus = (typeof CaseStatus)[keyof typeof CaseStatus];

/** Case */
export interface Case {
	/** Id (id) */
	Id: string;
	/** AccountId (reference) */
	AccountId: string | null;
	/** Attachment (base64) */
	Attachment__c: string | null;
	/** Big (long) */
	Big__c: number | null;
	/** CaseNumber (string) */
	CaseNumber: string;
	/** Channel (combobox) */
	Channel__c: CaseChannelCustom | (string & {}) | null;
	/** ClosedDate (datetime) */
	ClosedDate: string | null;
	/** ContactId (reference) */
	ContactId: string | null;
	/** IsClosed (boolean) */
	IsClosed: boolean;
	/** OwnerId (reference) */
	OwnerId: string;
	/** Priority (picklist) */
	Priority: CasePriority | null;
	/** Rate (percent) */
	Rate__c: number | null;
	/** Score (double) */
	Score__c: number | null;
	/** Secret (encryptedstring) */
	Secret__c: string | null;
	/** Status (picklist) */
	Status: CaseStatus;
	/** Subject (string) */
	Subject: string | null;
	/** Window (time) */
	Window__c: string | null;
}

export type CaseCreateInput = Partial<Pick<Case, "AccountId" | "Attachment__c" | "Big__c" | "Channel__c" | "ContactId" | "OwnerId" | "Priority" | "Rate__c" | "Score__c" | "Secret__c" | "Status" | "Subject" | "Window__c">>;

export type CaseUpdateInput = Partial<Pick<Case, "AccountId" | "Attachment__c" | "Big__c" | "Channel__c" | "ContactId" | "OwnerId" | "Priority" | "Rate__c" | "Score__c" | "Secret__c" | "Status" | "Subject" | "Window__c">>;

/** Active values of Contact.Interests__c (multipicklist). */
export const ContactInterestsCustom = {
	Golf: "Golf",
	Tennis: "Tennis",
} as const;
export type ContactInterestsCustom = (typeof ContactInterestsCustom)[keyof typeof ContactInterestsCustom];

/** Contact */
export interface Contact {
	/** Id (id) */
	Id: string;
	/** AccountId (reference) */
	AccountId: string | null;
	/** Anything (anyType) */
	Anything__c: unknown;
	/** Birthdate (date) */
	Birthdate: string | null;
	/** Email (email) */
	Email: string | null;
	/** FirstName (string) */
	FirstName: string | null;
	/** Interests (multipicklist) */
	Interests__c: string | null;
	/** LastName (string) */
	LastName: string;
	/** OwnerId (reference) */
	OwnerId: string;
}

export type ContactCreateInput = Pick<Contact, "LastName"> & Partial<Pick<Contact, "AccountId" | "Anything__c" | "Birthdate" | "Email" | "FirstName" | "Interests__c" | "OwnerId">>;

export type ContactUpdateInput = Partial<Pick<Contact, "AccountId" | "Anything__c" | "Birthdate" | "Email" | "FirstName" | "Interests__c" | "LastName" | "OwnerId">>;

/** Order Shipped */
export interface Order_Shipped__e {
	/** EventUuid (string) */
	EventUuid: string;
	/** Order Number (string) */
	Order_Number__c: string;
	/** ReplayId (string) */
	ReplayId: string;
	/** Shipped At (datetime) */
	Shipped_At__c: string | null;
}

export type Order_Shipped__eCreateInput = Pick<Order_Shipped__e, "Order_Number__c"> & Partial<Pick<Order_Shipped__e, "Shipped_At__c">>;

export type Order_Shipped__eUpdateInput = Partial<Pick<Order_Shipped__e, "Order_Number__c" | "Shipped_At__c">>;

/** Task */
export interface Task {
	/** Id (id) */
	Id: string;
	/** ActivityDate (date) */
	ActivityDate: string | null;
	/** OwnerId (reference) */
	OwnerId: string;
	/** Subject (string) */
	Subject: string | null;
	/** WhatId (reference) */
	WhatId: string | null;
}

export type TaskCreateInput = Partial<Pick<Task, "ActivityDate" | "OwnerId" | "Subject" | "WhatId">>;

export type TaskUpdateInput = Partial<Pick<Task, "ActivityDate" | "OwnerId" | "Subject" | "WhatId">>;

/** User */
export interface User {
	/** Id (id) */
	Id: string;
	/** Email (email) */
	Email: string;
	/** IsActive (boolean) */
	IsActive: boolean;
	/** LastName (string) */
	LastName: string;
	/** Username (string) */
	Username: string;
}

export type UserCreateInput = Pick<User, "Email" | "LastName" | "Username"> & Partial<Pick<User, "IsActive">>;

export type UserUpdateInput = Partial<Pick<User, "Email" | "IsActive" | "LastName" | "Username">>;

/**
 * Maps every generated sObject to its read, create and update types and its relationships.
 * Pass it to the client: `new SalesforceClient<SObjectRegistry>({ ... })`.
 */
export interface SObjectRegistry {
	Account: {
		read: Account;
		create: AccountCreateInput;
		update: AccountUpdateInput;
		parents: {
			Owner: "User";
			Parent: "Account";
		};
		children: {
			Cases: "Case";
			ChildAccounts: "Account";
			Contacts: "Contact";
		};
		externalIds: "External_Id__c" | "Id";
		fieldKinds: {
			CreatedDate: "datetime";
		};
		recordTypes: never;
		polymorphicParents: Record<never, never>;
	};
	Case: {
		read: Case;
		create: CaseCreateInput;
		update: CaseUpdateInput;
		parents: {
			Account: "Account";
			Contact: "Contact";
		};
		children: {
			Tasks: "Task";
		};
		externalIds: "Id";
		fieldKinds: {
			ClosedDate: "datetime";
			Window__c: "time";
		};
		recordTypes: "Complaint" | "Master" | "Question";
		polymorphicParents: {
			Owner: "Group" | "User";
		};
	};
	Contact: {
		read: Contact;
		create: ContactCreateInput;
		update: ContactUpdateInput;
		parents: {
			Account: "Account";
			Owner: "User";
		};
		children: {
			Cases: "Case";
		};
		externalIds: "Id";
		fieldKinds: {
			Birthdate: "date";
			Interests__c: "multipicklist";
		};
		recordTypes: never;
		polymorphicParents: Record<never, never>;
	};
	Order_Shipped__e: {
		read: Order_Shipped__e;
		create: Order_Shipped__eCreateInput;
		update: Order_Shipped__eUpdateInput;
		parents: Record<never, never>;
		children: Record<never, never>;
		externalIds: never;
		fieldKinds: {
			Shipped_At__c: "datetime";
		};
		recordTypes: never;
		polymorphicParents: Record<never, never>;
	};
	Task: {
		read: Task;
		create: TaskCreateInput;
		update: TaskUpdateInput;
		parents: Record<never, never>;
		children: Record<never, never>;
		externalIds: "Id";
		fieldKinds: {
			ActivityDate: "date";
		};
		recordTypes: never;
		polymorphicParents: {
			Owner: "Group" | "User";
			What: "Account" | "Case" | "Opportunity";
		};
	};
	User: {
		read: User;
		create: UserCreateInput;
		update: UserUpdateInput;
		parents: Record<never, never>;
		children: Record<never, never>;
		externalIds: "Id" | "Username";
		fieldKinds: Record<never, never>;
		recordTypes: never;
		polymorphicParents: Record<never, never>;
	};
}

/** Active picklist values per sObject and field, e.g. to loop over every status in a test. */
export const PICKLIST_VALUES = {
	Account: {
		Industry: ["Banking", "Energy"],
		Type: ["Customer", "Partner"],
	},
	Case: {
		Channel__c: ["Web", "Phone"],
		Priority: ["High", "Low"],
		Status: ["New", "Working", "Closed"],
	},
	Contact: {
		Interests__c: ["Golf", "Tennis"],
	},
} as const;

/** Record type DeveloperNames per sObject. Resolve ids with `sf.sobject(name).recordTypeId(developerName)`. */
export const RECORD_TYPES = {
	Case: ["Complaint", "Master", "Question"],
} as const;

/**
 * The API version these types were generated with. Pass it to the client so requests use the
 * same version: `new SalesforceClient<SObjectRegistry>({ apiVersion: API_VERSION, ... })`.
 */
export const API_VERSION = "v67.0";
